language: php
php:
  - '7.2'
services:
  - mysql
before_install:
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS kinikittest'
  - sudo mysql -e "GRANT ALL ON kinikittest.* to 'kinikittest'@'127.0.0.1' identified
    by 'kinikittest'"
before_script: composer install; cd test
script: phpunit .
after_success:
  - "../trigger_travis_build.sh kiniauth"
env:
  global:
    secure: T7DLLI6Am8/RFyboQkQi7Ifi3dd4WAeg0Cib917S0Se4WPAqCtsrVFbAF0b2pA3xHYKd7EjKY3yTXpvVmveTTKArIp4A0kYuBO45lfuapBROAIpWJt35sGcZtaJ7crLXQQJQFmEKzJkynifi9ILkNtysV+IzicmYXmmIHYrwgDxnEYMpaUCvcREfAF5JQpe1qe9M9thHtoEWxZh7QN5xr0MWhAn5dY27gDLj1Mb+mwvx/CSERed0vTEDfMeL3+10QNDu8bfKwjqqIObbaoex68eJgS/nDl1jBtV6miAskagtI40g09jMpCmtH29KR+8uZnqiqXc44TD5Ot7it6XVUC4SfuSrOXaHFvav4zRf7xop1IkWTw1k9z21r5KZvuQgmkaZW/hD/Dqf3bDoZBsHF6YUNhgJLBwDZTLOsHIlLL55QSw3a6epKqRcIVHCtsMHrgU6ZIzx780nCk8U0wFbtKzbqa+563qPgdxoOMj4uryg3RRp+wUI7PAMibBav9AXtfYcmTGU1AHb/+dFetBctenmonoEedjyuD399cEu6tONHzjEhda2a0IUI9YWMtEURkF5NOPOyUIjEfgAp5butrRoiwxCzXck0SUFpGo5nYt+8b+20Me4aWa/GOm7QEzQXcIkkty7YwrgCyt7SDAeIdUJtWW1jXarTjJBpH1RuW8=
notifications:
  slack:
    secure: VS0M+brzYjUHarjPrMwA711boEH9G8Sj0dP+pQ0XegfMSTXCX8YKJgY5BSb04Q6Mlkip18glbs0gcaq9wqFTOGwTt2BnnwVSe3zcumH5OAVDqecPLZzjkvpGhAtOg4WPySvLVNttQfMdrzXdJbL4uSunn5osDWvdmPT9XrR3BFYliI7tYwRjvXYTRYYE5dWkYtc0haqFuO5EoTIiD/NijoZTtnm9MtN+kLu/qETwRB/4NrbO/aBbUZ3+d5i/RzRUwcDmgr2G7NMLGJMs2jaKm9tDy8AEqMkQA6Ah87Rc/4RBdTsZh9KjmqDYL9UzgCGQ8RjBRaQ+4lS/C60lOJoUEo5EthK/1ng4vUhxFPBbpaUn18tX/9R/n9TZ+ZpgAOdDD687kh1ZPahxfpZKIoEfQf6Z5lEjG61yuve2zjssSV/cz3SinrXg11xHaTDJiuuasCPVCW/EJ8A8HZUysVnvoyDJq618/DzxRWhGpiXED6Lv/enkXXXgJnvsgaK4cIdgWGvsUqJ4JEmyWXFtP47KOMuimI0lVE7C8+TNl1UFNcgL5cSW6hQMdWfyqkIKtAJoTtPj95o5D+jNqFEgW8nCrZa4UvYXIoiPD8tcUvzS4PwP2mhQEoO8IKPrbVaGrGDR8p7xfjO5sv6dhXZqbnIVuk/zujaT5IaGAidy0OAUWFw=
