language: php
php:
  - '7.2'

services:
  - mysql

before_install:
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS kinikittest'
  - sudo mysql -e "GRANT ALL ON kinikittest.* to 'kinikittest'@'127.0.0.1' identified by 'kinikittest'"

before_script: composer install; cd test
script: phpunit .

after_success:
  - ../trigger_travis_build.sh kinicart

env:
  global:
    secure: AznXBp1kUC1XDLsJknqkWbzSUJJCfI1FbJyk73glyhERTfY7LLDukeURXAo/NgKfNURGMLSKWVWJLJKX8CUtCeSZzQ6sfK7+CRHn7gCPjMurI4rASF0OoKBARmVqiPeMtYcY58Vzj313PYxExWwkv0IJA9srEfiqJYPdgGmjSBcqbvY+lmJp/zogS+qUBHaVKbtwSUxzwEx0uAk6+gSqULrjXu+k27YFQwri3W7lmy9yxw0A0F08alFqLi59nd0VetvA5Var6h/Ido4U589eH+Qx3BeM+ZazwjjCL5yVMAwjFfzx1i5EPReQ/m9+2pTwDLdpQzwuLpFQ24wrduSXhsUkxNfVPwoLu9goEjQOodZoNnllsI2YB3Tfv63BR5Rh2s7YdZ2ALs6dVV1bc87DbIHVfrU2XOLJgfhUJcfjdkTmZZ7ZYpGtnvoXM7bH6w5dii1YCEIOh70GgjWlnqenVMhlgli9SIqNtGQf5E+c/hvUpLam7OVvEY7iyQm+XetThlK3z43QMePrUHZn4tkvYP/ACt/KGhNKQtGa6bs3cXwGTcfHy45pwBw+j5UBnW1RZdQBZKdSaaE8QDz3jrL0o1vCz9MNescspVSbYlWcLhZ7FlQ7dfJTom2gAwkeldPgqw50cfVZwA+gM4ZuIdSPQ1kLiAEPSltrDOx8Z720aCw=
